version: '3.8'

services:
  db:
    image: postgres:16
    container_name: db
    restart: always
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  minio:
    image: minio/minio
    container_name: minio
    command: server /data --console-address ":9001"
    restart: always
    env_file:
      - .env
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  minio-seed:
    image: minio/mc
    container_name: minio-seed
    depends_on:
      - minio
    env_file:
      - .env
    volumes:
      - ./database/tracks:/tracks
    entrypoint: >
      /bin/sh -c "
      echo '⏳ Waiting for MinIO...' &&
      sleep 5 &&
      mc alias set local http://minio:9000 $MINIO_ROOT_USER $MINIO_ROOT_PASSWORD &&
      mc mb local/${MINIO_BUCKET} || true &&
      mc anonymous set public local/${MINIO_BUCKET} &&
      echo '📦 Uploading tracks...' &&
      mc mirror /tracks local/${MINIO_BUCKET} &&
      echo '✅ Done'
      "

volumes:
  db_data:
  minio_data:
